/**
 * The Dossier schema is the contract between the LLM, the API routes,
 * and the UI. Every field is something we expect to render. Two-section
 * pipeline: §1 drugSummary and §2 patentTimeline are generated by separate
 * Gemini calls and stitched together client-side.
 */
import { z } from "zod";

export const CitationSchema = z.object({
  id: z.number().int().positive().describe("Stable id, referenced as [1], [2] in prose"),
  source: z.enum(["FDA_ORANGE_BOOK", "SEC_10K", "PATENT", "FDA_LABEL", "OTHER"]),
  reference: z
    .string()
    .describe(
      "Human-readable citation, e.g. 'FDA Orange Book, NDA 207103, Patent RE47739' or 'Pfizer 2024 10-K, p. 47, Product Revenue table'"
    ),
  url: z.string().url().optional(),
});
export type Citation = z.infer<typeof CitationSchema>;

export const DrugSummarySchema = z.object({
  name: z.string().describe("Display name including brand and generic, e.g. 'Ibrance (palbociclib)'"),
  originator: z.string().describe("Originator company, e.g. 'Pfizer Inc.'"),
  mechanismOfAction: z
    .string()
    .describe("1-2 sentences. Accurate, no marketing language."),
  indications: z.array(z.string()).describe("Approved US indications, concise"),
  annualRevenueUSD: z
    .number()
    .nullable()
    .describe(
      "Most recent published annual product revenue in USD. Null if you cannot cite a specific 10-K. NEVER guess."
    ),
  revenueYear: z.number().int().nullable().describe("Year of the revenue figure, or null"),
  revenueCitationId: z
    .number()
    .int()
    .nullable()
    .describe("Citation id pointing into citations[], or null if revenue is null"),
});
export type DrugSummary = z.infer<typeof DrugSummarySchema>;

export const PatentEventSchema = z.object({
  type: z.enum([
    "COMPOSITION_OF_MATTER",
    "METHOD_OF_USE",
    "FORMULATION",
    "PEDIATRIC_EXTENSION",
    "EXCLUSIVITY",
    "PROJECTED_GENERIC_LAUNCH",
  ]),
  label: z
    .string()
    .describe(
      "Short human label, e.g. 'Composition-of-matter (US RE47,739)' or 'Pediatric exclusivity bonus (+6 mo)'"
    ),
  date: z.string().describe("ISO yyyy-mm-dd"),
  citationId: z.number().int().describe("Citation id pointing into citations[]"),
  notes: z.string().optional().describe("Optional 1-sentence context for hover/tooltip"),
});
export type PatentEvent = z.infer<typeof PatentEventSchema>;

export const PatentTimelineSchema = z.object({
  events: z.array(PatentEventSchema),
  loeWindowStart: z.string().describe("ISO date of earliest meaningful patent expiry"),
  loeWindowEnd: z.string().describe("ISO date of projected generic launch (= last barrier)"),
  narrative: z
    .string()
    .describe(
      "2-3 sentence analyst summary. Tight, dispassionate. Cite events by date, not patent number."
    ),
});
export type PatentTimeline = z.infer<typeof PatentTimelineSchema>;

/** A complete dossier section (one of summary | timeline) bundled with its citations. */
export const DrugSummaryResponseSchema = z.object({
  drugSummary: DrugSummarySchema,
  citations: z.array(CitationSchema),
});
export type DrugSummaryResponse = z.infer<typeof DrugSummaryResponseSchema>;

export const PatentTimelineResponseSchema = z.object({
  patentTimeline: PatentTimelineSchema,
  citations: z.array(CitationSchema),
});
export type PatentTimelineResponse = z.infer<typeof PatentTimelineResponseSchema>;

/** The triage step's structured output. */
export const TriageResponseSchema = z.object({
  match: z.boolean(),
  ndaNumber: z.string().nullable(),
  ingredient: z.string().nullable(),
  tradeName: z.string().nullable(),
  rationale: z.string().describe("One-sentence reason this drug matches (or doesn't)"),
});
export type TriageResponse = z.infer<typeof TriageResponseSchema>;

/** The fully assembled dossier (server-side merged from the two responses). */
export const DossierSchema = z.object({
  drugSummary: DrugSummarySchema,
  patentTimeline: PatentTimelineSchema,
  citations: z.array(CitationSchema),
});
export type Dossier = z.infer<typeof DossierSchema>;

/** Scout filter coming in from the setup form. */
export const ScoutFilterSchema = z.object({
  therapeuticArea: z.string(),
  moleculeType: z.string(),
  loeWindowStart: z.string(),
  loeWindowEnd: z.string(),
  region: z.string(),
});
export type ScoutFilter = z.infer<typeof ScoutFilterSchema>;
