import { readFileSync } from "node:fs";
import { join } from "node:path";
import Link from "next/link";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { DrugSummaryCard } from "@/components/drug-summary-card";
import { PatentTimelineCard } from "@/components/patent-timeline-card";
import { CitationsSidebar } from "@/components/citations-sidebar";
import { DossierSchema, type Dossier } from "@/lib/schema";
import { formatDate } from "@/lib/format";

/**
 * For Block 5 we render directly from the cached golden dossier so we can
 * iterate UI without re-hitting Gemini. Block 6 will replace this with
 * three sequential client-side fetches to /api/scout/{triage,summary,timeline}.
 */
function loadGolden(): Dossier {
  const path = join(process.cwd(), "data", "golden-dossier.json");
  const payload = JSON.parse(readFileSync(path, "utf8"));
  return DossierSchema.parse(payload.dossier);
}

export default function DossierPage() {
  const dossier = loadGolden();

  return (
    <div className="mx-auto flex w-full max-w-7xl flex-col gap-8 px-6 py-10">
      {/* Top nav */}
      <div className="flex items-center justify-between">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="size-3.5" />
          Back to scouts
        </Link>
        <div className="inline-flex items-center gap-2 text-xs text-muted-foreground">
          <Sparkles className="size-3.5 text-primary" />
          <span>Generated by Pharma Scout</span>
        </div>
      </div>

      {/* Header */}
      <header className="flex flex-col gap-3">
        <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
          <Badge
            variant="outline"
            className="border-primary/40 text-primary"
          >
            Oncology · Small Molecule · US
          </Badge>
          <span>·</span>
          <span>LoE window 2027 — 2029</span>
        </div>
        <h1 className="text-4xl font-semibold tracking-tight">
          {dossier.drugSummary.name}
        </h1>
        <p className="text-muted-foreground max-w-2xl">
          {dossier.drugSummary.originator} ·{" "}
          <span className="text-foreground/80">
            Projected generic launch{" "}
            <span className="tabular-nums">
              {formatDate(dossier.patentTimeline.loeWindowEnd)}
            </span>
          </span>
        </p>
      </header>

      <Separator className="bg-border/60" />

      {/* Two-column layout: dossier sections + citations sidebar */}
      <div className="grid gap-8 lg:grid-cols-[1fr_320px]">
        <main className="flex flex-col gap-6 min-w-0">
          <DrugSummaryCard summary={dossier.drugSummary} />
          <PatentTimelineCard timeline={dossier.patentTimeline} />
        </main>
        <CitationsSidebar citations={dossier.citations} />
      </div>
    </div>
  );
}
